### ISSUE TITLE
Adding custom 503 error page?

### ISSUE THREAD

**Issue by kpheasey** [ajgon/opsworks_ruby#112]
During deployments, a 503 error can be thrown because there are no available connections during puma restart.

How would I add a custom 503 error page for the web server (apache/nginx)?  Handling it via CloudFront is very cumbersome.

### Side note

Would a PR for displaying a maintenance page during deployments be accepted?  Not showing a deployment page could mean that migrations run but the codebase has not been updated  (I know staged deployments could work around this, but it can be a lot of work to do that).  

I would add 2 recipes, one for showing the maintenance page and another for removing it.

**Comment by nickmarden** [comment]
@kpheasey I can think of two ways to do this:

1. Change the behavior of the default [nginx](https://github.com/ajgon/opsworks_ruby/blob/master/templates/default/appserver.nginx.conf.erb), [apache passenger](https://github.com/ajgon/opsworks_ruby/blob/master/templates/default/appserver.apache2.passenger.conf.erb) and [apache "upstream"](https://github.com/ajgon/opsworks_ruby/blob/master/templates/default/appserver.apache2.upstream.conf.erb) site configuration files to support maintenance pages. You might use something equivalent to this Apache stanza:

```
  RewriteCond %{DOCUMENT_ROOT}/system/maintenance.html -f # Test for maintenance mode
  RewriteCond %{REQUEST_URI} !\.(css|gif|jpg|jpeg|png)$ # Allow assets to be served
  RewriteCond %{SCRIPT_FILENAME} !maintenance.html # Don't apply this to the maintenance mode HTML file itself
  RewriteRule ^.*$ /system/maintenance.html [L] # Change every request to be a request for the maintenance mode page
```

As this would be a universal behavior, you'd want to add test in the `spec/unit/recipes` and `test/integration` directories to prove that your changes work.

Or,

2. Use the newly-added ["allow extensible webserver site customization"](https://github.com/ajgon/opsworks_ruby/commit/4efd1300ced4be90a7000a1646c01b8147758a1e) feature to override the template used to generate the application site configuration file that gets added to Apache or nginx for your app. In that overridden template, add a stanza like the one above. Since this would be your own local use of the cookbook, you could test this however you'd like.
