### ISSUE TITLE
Use an unix socket on Apache

### ISSUE THREAD

**Issue by waghanza** [ajgon/opsworks_ruby#140]
Hi,

Actually, when using `puma` as **appserver** (default) and `apache2` as **webserver**,  `Apache` listen to a port (`3000`).

`NginX` however listen to a **socket**.

I think, we **SHOULD** homogenize behavior (e.g : listen to a **socket** is both case).

As of **Apache** `2.3`, listen could be done via socket
@see https://httpd.apache.org/docs/2.4/fr/mod/mod_proxy_fcgi.html

What do you think ?

Regards,

**Comment by ajgon** [comment]
When I was implementing the very first version of apache2 driver, the idea was to use sockets as well. First, to keep it consistent with nginx, secondly, because it is (or should be) faster. However I had some issues with that. I can't recall what was it, but eventually gave up and ended up with ports. But the reason may be, that I don't have too much of experience with apache myself :)

However, I'm happy for a PR, from somebody with more apache experience than myself :)

**Comment by ajgon** [comment]
After hours of fighting I give up. I wasn't able to set up apache2 sockets to work properly with puma or unicorn. Managed to make apache to proxy request through the socket, however it sends some bizzare data instead of proper HTTP format and puma/unicorn throws an error. I'm happy to include this if anybody manages to solve this problem, but for now - I'm giving up.
