### ISSUE TITLE
Having adapter sidekiq will run duplicated jobs accross all instances?

### ISSUE THREAD

**Issue by krzkrzkrz** [ajgon/opsworks_ruby#174]
Just trying to understand something. If one has the following in custom JSON (in Stack -> Settings -> Edit -> Custom JSON):

```
      "worker": {
        "adapter": "sidekiq"
      }
```

And I have 5 instances running in a layer. Does that mean all 5 instances will also have sidekiq running in the background?

Wouldnt this mean, running a worker would run the same worker/job across all instances. Meaning 5 duplicated jobs?

In my other stack, using Chef 11. I had one instance in a layer. Layer executed a recipe that started sidekiq. Which meant, only one instance had sidekiq running in the background

**Comment by olbrich** [comment]
Yes.  If you have that set on a layer, then all instances in that layer will be running sidekiq workers.  It's not necessarily a bad idea to have the workers spread out across your layer.  If one of them goes away, the others will pick up the slack.  Sidekiq is smart enough to not run the same job on more than one machine, so it won't be run the same one multiple times.

If you really want to, a server can exist in multiple layers, so you can create a layer for running sidekiq and only put a subset of your servers in it.  Personally, I just run workers on each of my servers and turn the number of them down to 1 to minimize memory / cpu usage.  My background worker usage is pretty light, so that's not an issue for me.

**Comment by krzkrzkrz** [comment]
Hmmm, will give this a go and see how it plays out. Thanks for clarifying

**Comment by krzkrzkrz** [comment]
It got me thinking. Im our Rails app we are using https://github.com/ondrejbartas/sidekiq-cron for `cron` tasks. If we all instances are running sidekiq. And a cron task triggers. Will the same cron task run on all instances running sidekiq?

**Comment by olbrich** [comment]
according to the readme, you should be fine...

```
Checks for new jobs to schedule every 30 seconds and doesn't schedule the same job multiple times when more than one Sidekiq worker is running.

Scheduling jobs are added only when at least one Sidekiq process is running, but it is safe to use Sidekiq-Cron in environments where multiple Sidekiq processes or nodes are running.
```

Cron itself is a bit of a problem in opsworks as you generally only want 1 instance of cron running, so you have to play tricks to make sure it only gets run once.  

The library you mention should work fine, however.

**Comment by krzkrzkrz** [comment]
@olbrich Im curious. For sidekiq. You set process_count to 1. What about concurrency? Do you leave it at 5?

**Comment by olbrich** [comment]
Yes, we leave it at 5.  BTW, we are actually using a fork with support for shoryuken (which works with AWS SQS) instead of sidekiq, but it's configuration is very similar to sidekiq.

**Comment by krzkrzkrz** [comment]
Thanks for that piece of information
