### ISSUE TITLE
Question: should `bundle install` run before `before_migrate.rb`?

### ISSUE THREAD

**Issue by omnibs** [ajgon/opsworks_ruby#195]
### Expected Behavior

This line:

https://github.com/ajgon/opsworks_ruby/blob/1bb2fb5270fe104e5860fd6c2812517e5452a2ef/recipes/deploy.rb#L65

Makes `bundle exec` be executed before the callback triggered by:

https://github.com/ajgon/opsworks_ruby/blob/1bb2fb5270fe104e5860fd6c2812517e5452a2ef/recipes/deploy.rb#L71

### Actual Behavior

We enter the `before_migrate.rb` file without having run `bundle install`.

### Chef log including error

I don't really know how to grab a log that demonstrates this. I know how to pry into the `execute` blog and see things are queued for execution correctly, but I don't know how to verify when they are actually executed.

I concluded this while running a `before_migrate.rb` callback that runs a rake task, and rake wasn't installed by the time it tried to run:

```
execute "rake assets:download" do
  user deploy_user
  cwd release_path
  command(bundle_exec.("rake assets:download"))
  environment "RAILS_ENV" => rails_env
end
```

I tried to debug by changing the source of the `perform_bundle_install` to include `live_stream true` so I could hopefully see the `stdout` of `bundle install`, it didn't work.

I then copied `perform_bundle_install`'s `execute` block into my `before_migrate.rb` to see if it worked, it did.

I'm a newbie to Chef, so I might be wrong about all of this.

* Is my assumption correct, that `perform_bundle_install` is queueing `bundle install` to execute only after `before_migrate.rb`?
* Is that expected behavior?
* Is `before_migrate` the wrong place to run code that relies on external gems? Is there a more appropriate place for it?

**Comment by ajgon** [comment]
Hey,

It should work as you described. Maybe you have some troubles with gem paths or something else, that's why your application can't see the `rake` command?

The log should be available in your opsworks panel, after failing deploy, or in `/var/chef/runs` directory on your instance - please check [AWS OpsWorks troubleshoot article](https://docs.aws.amazon.com/opsworks/latest/userguide/troubleshoot-debug-log.html) for more information.

When you manage to find the logs, please paste them here - otherwise it's hard for me to determine what actually broke on your instance.
