### ISSUE TITLE
bundler & rubygems snafu

### ISSUE THREAD

**Issue by inopinatus** [ajgon/opsworks_ruby#203]
The release of Bundler 2 broke my setup cookbooks, because it is [incompatible with the system rubygems](https://bundler.io/blog/2019/01/04/an-update-on-the-bundler-2-release.html). To compensate I initially tried upgrading rubygems to 3.x. This in turn broke a bunch of `gem_package` resources because `--no-rdoc` was removed in rubygems 3 but Chef 12 still uses it.

Moving to rubygems v2.7.8 works for now, by adding this to my setup recipe:

    execute '/usr/bin/gem update --system 2.7.8 --no-document'

but this is interim at best because Ruby 2.6.0 ships with rubygems 3.x.

I've also logged an issue report with AWS Support about the broken `gem_package` resource although I currently have zero faith in the OpsWorks team's willingness to fix bitrot.

Any thoughts on best way to deal with this long term? A config option to manage bundler & rubygems version might extend the runway.

**Comment by ajgon** [comment]
I believe, the problem with rubygems 3.0 has been resolved, as I spinned up a new instance with rubygems 3 and bundler 2 - and everything worked out of the box.

However, there was still a problem with 2.x rubygems and projects using bundler 1.x due to fact, that fresh instance always was installing freshest bundler. What I did, I added a condition - if rubygems version is below 3.x always install bundler 1.x. This should resolve the issue.

Nice catch though, thank you!

**Comment by inopinatus** [comment]
Try running the setup a _second_ time on the same box (or any other recipe that uses `gem_package` resource to install a gem). In my tests it will break once rubygems 3 is installed.

**Comment by ajgon** [comment]
Oh, I see now.

Well this sucks, because it requires us to hack chef itself - this should not be opsworks_ruby responsibility. Besides, monkey-patching tends to rot and we may regret this later, when amazon updates chef to proper version.

So while it sucks, we probably need to wait for amazon to do their job, and in a meantime use workarounds...

**Comment by ajgon** [comment]
Ok, did some more research and it sucks even more, as most recent version of chef (`12.22.5`) still uses `--no-rdoc` and it looks like, chef team dropped the support for it.

So unless amazon updates chef to at least version `14` (I checked version `13` and it hardcodes `--no-rdoc` as well), we're stuck...

**Comment by inopinatus** [comment]
Yes I agree it's not a happy situation!

I had a couple of suggestions re. the patch, I've inlined them in the commit. Thanks for getting to this so quickly.
