### ISSUE TITLE
nginx + passenger

### ISSUE THREAD

**Issue by zeroedin** [ajgon/opsworks_ruby#219]
I'm curious if there are reasons why the nginx + passenger combo of webserver appserver is not supported?  Is it just lack of development time or has the feature just not been needed or just not yet requested?  Are any known technical reasons?  If not I may explore implementing the support.

**Comment by ajgon** [comment]
I don't have any experience with passenger, but to my understanding - there is an Apache module for it, while there is nothing like that for nginx. Also, passenger doesn't have any stand-alone server like puma or unicorn (or again, I may be not aware of it). That's why we don't support it. However, if there is a way - go for it! Every contribution is greatly apprecieated!

**Comment by zeroedin** [comment]
I'm giving it a go.

My reasoning for needing nginx + passenger is for WebSockets support as apache + passenger doesn't support.  https://www.phusionpassenger.com/library/config/apache/action_cable_integration/

Basically looking at how apache + passenger was integrated and using this as a guide from passengers website:
https://www.phusionpassenger.com/library/install/nginx/install/oss/bionic/

Can't promise anything but giving it a shot.
