### ISSUE TITLE
Database Pool Option Not Supported

### ISSUE THREAD

**Issue by haffla** [ajgon/opsworks_ruby#221]
Not sure about other frameworks, but in Rails the `pool` is quite a basic option that you likely want to tune in production. Is there a reason why there is no `pool` option? Otherwise I'd be happy to create a PR.

### Expected Behavior

I can specify a database pool size.

### Actual Behavior

It's not supported.

**Comment by ajgon** [comment]
Probably, because it wasn't in original Amazon recipes either. However, since this project drifted away from AWS baseline long time ago, if you wish, go for it. I'll be perfectly happy merging it :)

**Comment by cschulte22** [comment]
Setting a "pool" size in the database section works for me: https://opsworks-ruby.readthedocs.io/en/latest/attributes.html#database

It's not specified in the documentation, but any attributes you put there get passed through to the `database.yml` file.  I have it specified in the custom json on each layer in opsworks since we use different pool sizes for web vs background.

```
"deploy": {
  "your_app_name": {
    "database": {
      "adapter": "postgis",
      "pool": "5",
      "port": "5432",
      ...etc...
    }
  }
}
```

**Comment by zeroedin** [comment]
Confirmed, I actually just did this myself a couple days ago.

**Comment by haffla** [comment]
Oh cool, makes sense. Could have just given it a try. Thanks!
