### ISSUE TITLE
build-essential (~> 2.0) ? 

### ISSUE THREAD

**Issue by pjammer** [ajgon/opsworks_ruby#23]
build-essentials is on version 2.4.0 at time of writing. Was this pegged to the 2 year old one for compatibility reasons or something else? nginx is at the latest one, just wondering why this one wasn't.

**Comment by ajgon** [comment]
Yes, the lock is mainly due to `nginx` compatibility, since this cookbook has `build-essentials` frozen at that version as well. I'm not sure, why I introduced it here - the `nginx` should force it anyway.

It would remain frozen with that version for some time, since `nginx 3.0.0` is still in development, and they would change the API significantly, which means I would have to alter this cookbook as well.

Having said that - I removed the requirement from `metadata.rb` ;)
