### ISSUE TITLE
Rails 5.1 - Yarn or npm install?

### ISSUE THREAD

**Issue by kpheasey** [ajgon/opsworks_ruby#80]
With Rails 5.1 adding native support for webpack/yarn, I would like to add this functionality to my deployment.  

Is there any sort of hook I can use to call `npm install` or `yarn install` after the latest revision has been fetched, but before asset precompile?

Ideally, I would like to add the node_packages folder to shared folders as well.

**Comment by inopinatus** [comment]
I'm doing `yarn install` in my `deploy/before_symlink.rb`.

**Comment by kpheasey** [comment]
@inopinatus Do you mind sharing that file?  Also, how are you installing nodejs / yarn?

**Comment by ajgon** [comment]
As @inopinatus mentioned - you can do this via `before_` hooks. As for `nodejs`/`yarn` [there is a cookbook for that](https://supermarket.chef.io/cookbooks/nodejs). It allows you to configure both nodejs versions and preinstalled global packages, for example:

```json
{
  "nodejs": {
    "version": "6.10.3",
    "npm_packages": [
      {
        "name": "yarn"
      }
    ]
  }
}
```

**Comment by kpheasey** [comment]
Just wanted to add that yarn installation via npm is not recommend; https://yarnpkg.com/lang/en/docs/install/#alternatives-tab

That being said, the above solution worked for me.

**Comment by ajgon** [comment]
I think, the easiest way to do this properly then, is to add custom recipe to setup phase with repository, and yarn installation, something like (if you use Debian):

```ruby
# recipes/yarn.rb

apt_repository 'yarn' do
  uri          'https://dl.yarnpkg.com/debian/'
  arch         'amd64'
  distribution 'jessie'
  components   ['main']
  key          'https://dl.yarnpkg.com/debian/pubkey.gpg'
end

package 'yarn'
```

**Comment by conarro** [comment]
I had success using this cookbook to install Yarn:
https://github.com/aspyatkin/yarn-cookbook

I already wrapped the `opsworks_ruby` recipes in my own cookbook, so it was easy to include. I just added `include_recipe 'yarn::install_package'` into my custom `setup.rb` recipe (which already includes the opsworks_ruby setup).

**Comment by willkoehler** [comment]
BTW the `key` attribute of `apt_repository` doesn't work in OpsWorks with Ubuntu 16.10+. It silently fails to setup the new key. This was fixed in Chef a while ago (see https://github.com/chef/chef/commit/6309edcc89e6b606f7b5cf8e82c20bbdd8d91487), but the version of Chef that OpsWorks uses (12.18.31) doesn't include the fix.

The work-around is to install the key manually first. Here's my recipe to install Yarn via OS package

```ruby
# Add a new PPA for Yarn and install Yarn package
#
# This will probably be built into opsworks_ruby in the future. See https://github.com/ajgon/opsworks_ruby/pull/216
# But for now see: https://github.com/ajgon/opsworks_ruby/issues/80
# Official Yarn install steps for Ubuntu https://yarnpkg.com/lang/en/docs/install/#debian-stable

# We need to install apt keys manually in Ubuntu 18.04. The "key" attribute of apt_repository doesn't work
# See https://github.com/chef/chef/issues/5831 (referenced from https://github.com/chef-cookbooks/apt/issues/216)
# Change to Chef that fixes this https://github.com/chef/chef/commit/6309edcc89e6b606f7b5cf8e82c20bbdd8d91487
# This fix doesn't appear to be in the version of Chef that OpsWorks uses (12.18.31)
# https://github.com/chef/chef/compare/v12.18.31...master#diff-bebf53f73971986ff320054ee72c1293L150
# This appears to be the Ubuntu change that required the updates to Chef https://askubuntu.com/a/846877/376611
execute 'setup yarn repository key' do
  command 'curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -'
end

apt_repository 'yarn' do
  uri 'https://dl.yarnpkg.com/debian/'
  distribution 'stable'
  components ['main']
  # (doesn't work in Ubuntu 16.10+) key 'https://dl.yarnpkg.com/debian/pubkey.gpg'
  action :add
end

package 'yarn'
```

**Comment by kpheasey** [comment]
I've made a PR that includes all this functionality, since it's a common Rails requirement now; #216

**Comment by willkoehler** [comment]
@kpheasey Thanks for the PR 👍 

FYI I believe that the yarn cookbook added in your PR has the same problem with apt keys in Ubuntu 16.10+ that I worked around in my solution above. See https://github.com/aspyatkin/yarn-cookbook/blob/8e0c4237d91fb3f6a8cb9f50bc4def2638d1c457/recipes/repository.rb#L18

This is a tricky problem to find a good solution for. While the actual solution is straightforward, my question is where do we put it? It can't be solved by a PR upstream in the Yarn cookbook because it's caused by the combination of an outdated version of Chef in combination with a newer version of Ubuntu. Surely that's not a problem that the Yarn cookbook should need to worry about.

I think ultimately it falls to something in the opsworks_ruby cookbook since it's this cookbook's job to make Ruby + OpsWorks + various OSs work together. The solution is a bit of a hack (manually adding the key with `curl` + `apt-key`) and is dependent on the OS (Ubuntu 16.10+). I don't like a conditional `execute` command in combination with a conditional `key` attribute in the `apt_repository` command, but that's the shape the solution is taking in my mind. Maybe you have a better idea?

**Comment by ajgon** [comment]
@willkoehler Looks like chef 12 also have this fix included: https://github.com/chef/chef/commit/54e75c431c0d45653b857e61412d8f85de69fbab . All versions from `12.20.3` include this fix ([source](https://github.com/chef/chef/commits/chef-12?after=a9a33d08110509f9c5d176bb4688a410c863d799+209)). Would this help resolve the issue? (`opsworks_ruby` is perfectly fine to work with any chef version from `12.x` scope)

**Comment by kpheasey** [comment]
@willkoehler 
> FYI I believe that the yarn cookbook added in your PR has the same problem with apt keys in Ubuntu 16.10+ that I worked around in my solution above. See https://github.com/aspyatkin/yarn-cookbook/blob/8e0c4237d91fb3f6a8cb9f50bc4def2638d1c457/recipes/repository.rb#L18

The `yarn-cookbook` does not set a default value for `node['yarn']['package']['repository']['key']` and `opsworks_ruby` doesn't either.  I believe it's a nil value unless explicitly set by your opsworks configuration.

**Comment by willkoehler** [comment]
> Looks like chef 12 also have this fix included: [chef/chef@54e75c4](https://github.com/chef/chef/commit/54e75c431c0d45653b857e61412d8f85de69fbab) . All versions from `12.20.3` include this fix ([source](https://github.com/chef/chef/commits/chef-12?after=a9a33d08110509f9c5d176bb4688a410c863d799+209)).

@ajgon That's a good point and could be part of a solution. Unfortunately, from what I can tell, OpsWorks uses Chef v12.18.31, which doesn't have that fix. I believe the Chef version used by OpsWorks is v12.18.31 because I see the following in the deploy logs:

> . . .
[2019-07-01T15:41:14+00:00] INFO: Started chef-zero at chefzero://localhost:8889 with repository at /var/chef
One version per cookbook
data_bags at /var/chef/runs/7b1cd82c-75aa-480c-8811-54b8eeac331b/data_bags
nodes at /var/chef/runs/7b1cd82c-75aa-480c-8811-54b8eeac331b/nodes
>
> [2019-07-01T15:41:14+00:00] INFO: Forking chef instance to converge...
[2019-07-01T15:41:14+00:00] INFO: *** Chef 12.18.31 ***
[2019-07-01T15:41:14+00:00] INFO: Platform: x86_64-linux
[2019-07-01T15:41:14+00:00] INFO: Chef-client pid: 29902
[2019-07-01T15:41:16+00:00] INFO: Setting the run_list to ["recipe[opsworks_ruby::deploy]"] from CLI options
. . .

I have several OpsWorks stacks with deployments over the last 6 months (some of the stacks have been created as recently as a few weeks ago) and they all use Chef v12.18.31. I don't see any way to change this Chef version.

@kpheasey I believe `yarn-cookbook` sets the key here  for the `debian` platform https://github.com/aspyatkin/yarn-cookbook/blob/fd1491d3421ff9549e89df3cf576f222a042021c/attributes/default.rb#L20 (excerpt below)

```ruby
default['yarn']['package'].tap do |package|
  package['upgrade'] = true
  package['version'] = nil

  package['repository']['uri'] = case node['platform_family']
                         when 'debian' then 'https://dl.yarnpkg.com/debian/'
                         when 'rhel', 'amazon' then 'https://dl.yarnpkg.com/rpm/'
                         end
  package['repository']['key'] = case node['platform_family']
                         when 'debian' then 'https://dl.yarnpkg.com/debian/pubkey.gpg'
                         when 'rhel', 'amazon' then 'https://dl.yarnpkg.com/rpm/pubkey.gpg'
                         end
  package['repository']['distribution'] = 'stable'
  package['repository']['components'] = %w(
    main
  )
end
```

This is consistent with the key I am configuring manually in my solution. Without that key, Ubuntu won't install the package from a third-party URL (https://dl.yarnpkg.com/debian/)

**Comment by ajgon** [comment]
Yeah, seems like Amazon doesn't care about OpsWorks anymore, as the last Chef upgrade was [over two years ago](https://docs.aws.amazon.com/opsworks/latest/userguide/agentchanges.html).

**Comment by ajgon** [comment]
[There is a way](https://aws.amazon.com/blogs/mt/updating-chef-client-on-aws-opsworks-for-chef-automate-nodes/) to automatically update chef on OpsWorks. However it needs to be initiated by user, I can't do this from `opsworks_ruby` cookbook, as at some point it needs to kill old chef and start a new one. This would cause the opsworks setup to fail. So that's a dead end for us, unfortunatelly :(

**Comment by kpheasey** [comment]
Opsworks definitely seems like a dead service. Containers have taken over.  I've been working on cloud formation to run my workloads to run on ecs with code pipeline and code build.  It could make a nice community project if I ever get it finished!

**Comment by zeroedin** [comment]
@ajgon that is something I hope to try and reach out to someone at AWS re:Invent this year.  That is if I can get work to send me again.  I'm just not working at a large enough scale to need to the complexity of containers or chef automate service.  Hoping to see if I can get an answer to if support is going to be cut.

**Comment by inopinatus** [comment]
I have successfully upgraded an OpsWorks-managed instance to Chef 14.  It requires only the official Chef in-place-upgrade cookbook added to setup, plus a couple of simple shims.

https://github.com/inopinatus/chef-upgrade

**Comment by ajgon** [comment]
@inopinatus That's awesome!

I used your code in this commit <https://github.com/ajgon/opsworks_ruby/commit/609633bb6c39c6c02ae6b9ce405424882a852d05> to allow chef upgrade directly from `opsworks_ruby` cookbook. Are you okay with "honorable mentions" which I included in the code about your work, or do you like me to add them elsewhere as well?

**Comment by inopinatus** [comment]
No that is fine as it is! No more attribution required, I'm very happy to see it included. It's a simple implementation, I just needed to find the exact pressure points that made it possible.

Hopefully some will find it useful to extend the life of their stacks.
